export const types = {
    EDIT_ITEM_ACTION: 'EDIT_ITEM_ACTION',
    DELETE_ITEM_ACTION: 'DELETE_ITEM_ACTION',
    ADD_ITEM_ACTION: 'ADD_ITEM_ACTION',
    DONE_ITEM_ACTION: 'DONE_ITEM_ACTION',
    CHANGE_ITEM_ACTION: 'CHANGE_ITEM_ACTION'
};